services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: defaultdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: lmao
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80" # Maps localhost:3000 to nginx
    depends_on:
      - backend

  backend:
    build:
      context: ./api
    ports:
      - "4000:4000" # Maps localhost:5000 to the backend service
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    command:
      [
        "./wait-for-it.sh",
        "db:3306",
        "--",
        "npx",
        "prisma",
        "migrate",
        "dev",
        "--name",
        "init",
      ]
