-- AlterTable
ALTER TABLE `account` MODIFY `debit` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `credit` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `buys` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `dye` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `outsource` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `yarn` BOOLEAN NOT NULL DEFAULT false;
