-- AlterTable
ALTER TABLE `productFeasibilityForm` MODIFY `date` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `attendees` JSON NULL,
    MODIFY `yearlyProductionCount` INTEGER NULL,
    MODIFY `startDateGoal` DATETIME(3) NULL,
    MODIFY `marketReady` BOOLEAN NULL,
    MODIFY `demandReady` BOOLEAN NULL,
    MODIFY `legalReady` BOOLEAN NULL,
    MODIFY `testReady` BOOLEAN NULL,
    MODIFY `productionReady` BOOLEAN NULL,
    MODIFY `measurementReady` BOOLEAN NULL,
    MODIFY `rawMaterialCost` DOUBLE NULL,
    MODIFY `productionCost` DOUBLE NULL,
    MODIFY `process` JSON NULL,
    MODIFY `material` JSON NULL,
    MODIFY `auxEquipment` JSON NULL,
    MODIFY `machine` JSON NULL,
    MODIFY `costs` JSON NULL,
    MODIFY `cost` DOUBLE NULL,
    MODIFY `customerBudget` DOUBLE NULL,
    MODIFY `priceDifferencePercent` DOUBLE NULL,
    MODIFY `suitable` BOOLEAN NULL,
    MODIFY `costsCovered` BOOLEAN NULL;
